package org.o7planning.mychatapp;

import android.content.Intent;
import android.os.Bundle;
import android.text.TextUtils;
import android.util.Log;
import android.widget.Button;
import android.widget.TextView;
import android.widget.Toast;

import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;

import com.google.android.gms.tasks.OnCompleteListener;
import com.google.android.gms.tasks.Task;
import com.google.firebase.auth.AuthResult;
import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.auth.FirebaseUser;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;

import java.util.HashMap;

public class RegisterActivity extends AppCompatActivity {

    Button mloginButton;
    TextView mEmailTextView;
    TextView mPasswordTextView;
    TextView mUsernameTextView;

    String msg = " \n n \n n \n";

    private FirebaseAuth mAuth;
    DatabaseReference databaseReference;

    public void onCreate(Bundle B) {
        super.onCreate(B);
        setContentView(R.layout.activity_register);

        mloginButton = findViewById(R.id.register_button);
        mEmailTextView = findViewById(R.id.email);
        mPasswordTextView = findViewById(R.id.password);
        mUsernameTextView = findViewById(R.id.username);

        // Initialize Firebase Auth
        mAuth = FirebaseAuth.getInstance();

        mloginButton.setOnClickListener(v -> {

            String email = mEmailTextView.getText().toString();
            String password = mPasswordTextView.getText().toString();
            String username = mUsernameTextView.getText().toString();

            if (TextUtils.isEmpty(username) || TextUtils.isEmpty(email) || TextUtils.isEmpty(password)) {
                Toast.makeText(RegisterActivity.this, "All fields are required", Toast.LENGTH_SHORT).show();
            } else {
                registeruser(email, password, username);
            }


        });

    }

    public void registeruser(String email, String password, String username) {

        mAuth = FirebaseAuth.getInstance();

        mAuth.createUserWithEmailAndPassword(email, password)
                .addOnCompleteListener(this, new OnCompleteListener<AuthResult>() {
                    @Override
                    public void onComplete(@NonNull Task<AuthResult> task) {
                        if (task.isSuccessful()) {

                            //ADD THE USER TO DATABASE

                            FirebaseUser firebaseUser = mAuth.getCurrentUser();   // user has email , password and an id
                            String userId = firebaseUser.getUid();  // generated by firebase

                            // created an area by name userId where we will place the user
                            databaseReference = FirebaseDatabase.getInstance().getReference("users").child(userId);

                            HashMap<String, String> hashMap = new HashMap<>();
                            hashMap.put("id", userId);
                            hashMap.put("username", username);
                            hashMap.put("imageurl", "default");
                            hashMap.put("status", "offline");
                            hashMap.put("search", username.toLowerCase());

                            // below code is ok but we need confirmation about whether it has been done or not so
                            // thats why there's addOnCompleteListener which works after/on setValue()
//                            databaseReference.setValue(hashMap);

                            databaseReference.setValue(hashMap).addOnCompleteListener(new OnCompleteListener<Void>() {
                                @Override
                                public void onComplete(@NonNull Task<Void> task) {

                                    if (task.isSuccessful()) {
                                        Toast.makeText(RegisterActivity.this, "Successfully added to Database.",
                                                Toast.LENGTH_SHORT).show();

                                        Intent intent = new Intent(RegisterActivity.this, MainActivity.class);
                                        intent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TASK | Intent.FLAG_ACTIVITY_NEW_TASK);   // FLAG_ACTIVITY_CLEAR_TOP too worked but what is written is better as it doesnt reproduce the main page again on back button click
                                        startActivity(intent);

                                    } else {
                                        Toast.makeText(RegisterActivity.this, "Database insertion failure",
                                                Toast.LENGTH_SHORT).show();
                                    }

                                }
                            });

                        } else {
                            Toast.makeText(RegisterActivity.this, "Either Email is already registered or ur password length <6",
                                    Toast.LENGTH_SHORT).show();

                        }

                    }
                });

    }
}
